"""empty message

Revision ID: 28d501854c89
Revises: 00c41897c12b
Create Date: 2023-09-04 15:15:35.083845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28d501854c89'
down_revision = '00c41897c12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour', sa.Time(timezone=120), nullable=False))
        batch_op.drop_column('paid')
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('hour')

    # ### end Alembic commands ###
