"""empty message

Revision ID: 720f20384d49
Revises: 3ae4a6f9af92
Create Date: 2023-09-04 15:48:36.722060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720f20384d49'
down_revision = '3ae4a6f9af92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.alter_column('comments_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=240),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.alter_column('comments_id',
               existing_type=sa.String(length=240),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
