"""empty message

Revision ID: e6b913d21a6d
Revises: 438cc43dc5ab
Create Date: 2023-09-04 16:49:14.777562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b913d21a6d'
down_revision = '438cc43dc5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.String(length=240), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.drop_constraint('class_comments_id_fkey', type_='foreignkey')
        batch_op.drop_column('comments_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('class_comments_id_fkey', 'comments', ['comments_id'], ['id'])
        batch_op.drop_column('price')
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
