import React from "react";
import "../../styles/termsAndConditions.css"

export const TermsAndConditions = () => {
    return (
        <>

            <div className="terms-div">
                <div className="d-flex w-100 justify-content-between">
                    <div className="col terms-text">
                        <h1 className="title-terms mt-5 mb-5 text-center">LessonBucket Terms and Conditions of Use</h1>
                        <p className="text-terms mx-5 mt-3 mb-5">Below are the Terms of Use for our "Platform." We recommend reading the complete text of the Terms of Use as it is our legally binding agreement.
                            By using our Platform, you agree to our Terms of Use, which represent a legally binding agreement between you and LessonBucket.
                            If you violate the rules, we may suspend or cancel your account.</p>
                        <h5 className="title-terms mx-5">Participants and organizers</h5>
                        <ol className="text-terms mx-5 mt-3 mb-3 col">
                            <li className="text-terms mx-5 mt-3 mb-3">Using our Platform involves interacting with people and doing things in the real world, which can sometimes lead to unexpected situations. We cannot control what happens in the real world, and we are not responsible for it. Use common sense when interacting with others.
                                Your content and other people's content</li>
                            <li className="text-terms mx-5 mt-3 mb-3">You are responsible for your Content, which means any information or other material posted on our Platform. Your Content must comply with our Terms of Use, including Content and Use Policies, Event Policies, and Intellectual Property Dispute Policies. We are not responsible for the Content you post. However, we need you to grant us a license to use this Content so that we can improve, develop, and protect our Platform for you and others.</li>
                            <li className="text-terms mx-5 mt-3 mb-3">We are not responsible for the Content posted by members or messages posted by members through our Platform. We generally do not review Content before it is posted. If you see Content that violates our Terms of Use, you can report it as inappropriate.</li>
                        </ol>
                        <h5 className="title-terms mx-5">The platform</h5>
                        <ol className="mx-5 mt-3 mb-3">
                            <li className="text-terms mx-5 mt-3 mb-3">We strive to ensure that our Platform is always available and functional, but we cannot guarantee it. Sometimes things do not go as planned. We apologize in advance.</li>
                            <li className="text-terms mx-5 mt-3 mb-3">We are constantly improving our Platform. This means that we may change or discontinue certain features of it. By using it, you agree to the limitations and exclusions of liability in our Terms of Use. You also agree to resolve any disputes you may have with us as described in the Terms of Use. If you do not live in the European Union, you agree to be bound and waive your right to seek protection from a judge or court of law. Claims can only be filed on an individual basis and not as part of a class action.</li>
                            <li className="text-terms mx-5 mt-3 mb-3">You likely reside in a country where applicable laws stipulate different or additional rights and obligations. These Terms of Use will specify areas of divergence.</li>
                        </ol>
                        <h5 className="title-terms mx-5">Terms of use</h5>
                        <p className="text-terms mx-5 mt-3 mb-3">Last updated: 11/2/2023</p>
                        <p className="text-terms mx-5 mt-3 mb-3">Our Terms of Use contain important information about your legal rights. To aid in understanding, we have provided summaries and tips in these gray boxes. These summaries are not part of the official conditions, and it is important that you carefully read the content of each section.</p>
                        <h6 className="text-terms mx-5 mt-3 mb-3"><b>1. This Agreement</b><br /></h6>
                        <p className="text-terms mx-5 mt-3 mb-3">
                            <b>Summary:</b> You agree to follow some basic rules when using the Meetup Platform. These rules are described in these Terms of Use, including the related policies and guidelines discussed below. We may change these rules.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>1.1 The Agreement.</b> LessonBucket allows you and other members to organize events or meetings outside of the Internet, in the real world. The terms "LessonBucket," "we," "us," and "our" refer to LessonBucket and our parent companies, subsidiaries, and affiliates. We use the terms "you" and "your" to refer to anyone who uses our Platform and any company or person who uses the Platform on behalf of a company. We use the term "Platform" to refer to any website, application, or service offered by LessonBucket, including the content we offer and the electronic communications we send. We provide you with our Platform under these Terms of Use. We use the terms "Terms of Use" and "Agreement" interchangeably to refer to this document along with our Content and Use Policies, Event Policies, Organizer and Organization Team Standards, and Membership Restrictions. By using the platform, you indicate that you accept this Agreement. If you use the Platform for a company, you accept this Agreement on behalf of that company and affirm that you have the authority to bind that company to the conditions set forth in this Agreement. If you do not accept or cannot accept this Agreement, please do not use our Platform.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>Tips:</b> We have included summaries and tips to provide an overview of some legal concepts and answer common questions, but the text of these summaries and tips is provided solely to facilitate your understanding and has no legal effect.</p>
                        <p className="text-terms mx-5 mt-3 mb-3">These Terms of Use are an agreement between you and LessonBucket, not between you and any other member.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>1.2 Revisions to this Agreement.</b> We may modify this Agreement as needed. If we make any modifications, we will inform you by posting the most recent version and updating the date at the top of this page. If we make a substantial modification to this Agreement, we will notify you in some other way, for example, by sending you an email or displaying a prominent notice on our Platform. If you continue to use the Platform after the effective date of any modification, it will mean that you accept the revised Agreement. If you do not wish to accept the revised Agreement, you may close your account.</p>
                        <h6 className="text-terms mx-5 mt-3 mb-3"><b>2. Your Account and Being a Member</b></h6>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>Summary:</b> You need to be at least 18 years old to use our Platform. LessonBucket organizers control Content and membership in LessonBucket events. However, we can remove any Content you post or cancel your account at any time.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>2.1 Admission.</b> Our Platform is available to anyone who is at least 18 years old. You affirm that you are at least 18 years old.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>2.2 Modification, Suspension, and Cancellation of Your Account.</b> We may modify, suspend, or cancel your account or access to the Platform if, in our sole and exclusive discretion, we determine that you have violated this Agreement, including any of the policies or guidelines that are part of this Agreement, which benefit the LessonBucket community, or to protect our brand or Platform. If this happens, we will notify you of the reasons for the modification, suspension, or cancellation of your account. We may also delete member accounts that have been inactive for an extended period of time. Write to us at policy@LessonBucket.com if you believe that the modification, suspension, or cancellation of your account is due to an error.
                            A member with the ability to moderate or manage a particular portion of our Platform may also, at their sole and exclusive discretion, modify, suspend, or cancel your access to that portion of the Platform.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>2.3 Account Information and Security.</b> When you register, you provide us with certain basic information, including an email address and a password. Keep your email address and other account information up to date. Also, you agree to maintain the security and confidentiality of your password (otherwise, we may have to deactivate your account). We strongly recommend that you choose a password that is difficult to guess and that you do not use on other online accounts or services, and that you follow other recommended password security practices to prevent unauthorized access to your account as much as possible. You are solely responsible for the consequences of not maintaining such security and confidentiality, for example, if you share your account credentials with others. If anyone is using your password or has accessed your account without your permission, write to us at abuse@LessonBucket.com.</p>
                        <h6 className="text-terms mx-5 mt-3 mb-3"><b>3. Your Content and Privacy</b></h6>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>Summary:</b> You are responsible for the Content you post on our Platform. You grant us a license to use this Content to operate, improve, promote, and protect LessonBucket and our Platform. Our Privacy Policy describes how we collect and use the information you provide about yourself and information that may be associated with you, and explains the limited ways in which we may share this information.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>3.1 Your Content.</b> You are responsible for the Content you post on the Platform or otherwise provide to LessonBucket. By "Content," we mean the information, material, and any other content you post on the Platform or send to us in any way. We provide examples of Content below:
                            • Material that organizers and members typically post on the Platform, such as information about LessonBucket events, comments, and photos.
                            • All opinions, suggestions, and other communications you submit or direct to LessonBucket.</p>
                        <p className="text-terms mx-5 mt-3 mb-3">As the owner of your Content, you agree, among other things, that:
                            • You have all necessary permissions, rights, and licenses (including copyright, trademark, contract rights, privacy rights, or publicity rights) to provide the Content to the Platform and LessonBucket.
                            • Your Content does not include personal, private, or confidential information owned by other individuals.
                            • Your Content does not infringe the rights of any person or entity.</p>
                        <p className="text-terms mx-5 mt-3 mb-3">You also agree that both you and your Content comply with this Agreement, including our Content and Use Policies, Event Policies, Organizer and Organization Team Standards, Membership Restrictions, and Intellectual Property Policies. You also agree that we may remove metadata related to your Content.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>3.2 License Granted by You on the Content.</b> We do not claim ownership of your Content. However, in order for us to operate, improve, promote, and protect LessonBucket and our Platform, and to ensure that we do not infringe any rights you may have in your Content, you hereby grant LessonBucket a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sublicensable, and transferable right and license (including a waiver of any moral rights) to use, host, store, reproduce, modify, publish, publicly display, publicly perform, and distribute your Content, as well as to create derivative works from it and to market and exploit copyright, trademark, advertising, and database rights you have in your Content. This license would allow your Content to remain on the Platform, even after you cease to be a member of a LessonBucket group or the Platform.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>Advice:</b> This license does not grant us ownership of any part of your Content. It simply grants us and the members the right to use it in connection with the Platform. This license continues even if you close your account because it is necessary for us to operate the Platform.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>3.3 Privacy.</b> LessonBucket collects registration information and other information about you through our Platform. Refer to our Privacy Policy and Cookie Policy for more information on how we collect, use, and disclose this information. These policies do not govern the use of information you provide to third parties, such as organizers and other members of the LessonBucket Platform.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>Advice:</b> LessonBucket cannot control how other members use the information you provide to them; therefore, it is very important to use common sense and good judgment when sharing information with others on our Platform.</p>
                        <h6 className="text-terms mx-5 mt-3 mb-3">4. Your use of our Platform</h6>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>Summary:</b> We require you to follow our policies and guidelines when using our Platform. We do not assume any responsibility for the Content posted by anyone on our Platform.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>4.1 Our policies, guidelines, and applicable laws.</b> When using our Platform, we require you to comply with the Usage and Content Policies, Event Policies, Organizer and Organizer Team Standards, Membership Restrictions, and Trademark Use Guidelines. You also agree to comply with all applicable laws, rules, and regulations and not to violate or infringe the rights of any third party. The Platform occasionally uses third-party services to provide certain features and services to our members, some of which may require compliance with the terms governing such features and services. For example, some areas of our Platform offer mapping services provided by Google Maps and Google Earth. By using these mapping services on the Platform, you agree to adhere to the Additional Google Maps/Google Earth Terms of Use. If you violate this Agreement, we may modify, suspend, or terminate your account or access to the Platform at our sole discretion, in which case we will communicate the reasons to you. Please email policy@LessonBucket.com if you believe that the modification, suspension, or termination was made in error.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>4.2 Content from other people.</b> LessonBucket does not control the Content of other members. If we become aware of the existence of inappropriate Content on our Platform, we reserve the right to investigate and take appropriate action, but we have no obligation to monitor the Content of other members and assume no responsibility for it.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>4.3 Interactions with other people.</b> LessonBucket is not part of any offline plan made through our Platform. LessonBucket does not conduct or require background checks on members and does not attempt to verify the truth or accuracy of statements made by members. LessonBucket makes no representations or warranties regarding the conduct or Content of any member or their interactions with you.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>Advice:</b> Use common sense and good judgment when using our Platform and interacting with other members, both on our Platform and at LessonBucket events. If you believe that another member's behavior is inappropriate, you can report it by emailing abuse@LessonBucket.com.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>4.4 Prohibited uses of the Platform.</b> Our Platform contains exclusive and confidential information and is protected by intellectual property laws. Unless expressly permitted in this Agreement, you agree, directly or indirectly, not to (a) use, host, store, reproduce, modify, publish, display and publicly perform, distribute, or create derivative works of the Platform or any of its parts; (b) remove or alter the Platform's ownership notices; (c) reverse engineer, disassemble, decompile, or attempt to discover the source code or structure, sequence, or organization of the Platform, nor (d) rent, lease, resell, distribute, or use the Platform for commercial purposes not contemplated in this Agreement. You also agree not to use the Platform to request or collect (i) personal data of other people unless necessary for the administration or participation in a group or event, nor (ii) sensitive personal data, as determined and treated in accordance with applicable law (including, for example, health information, social security numbers, or other government identifiers).</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>4.5 Platform security.</b> You agree that you may not, directly or indirectly, (a) extract data from the Platform for commercial purposes not permitted by these Terms of Use, whether by using an automated system or software operated by a third party or otherwise (mass scraping of screens, data, or web elements); (b) engage in any activity that interferes with or disrupts, is designed to interfere with or disrupt, or imposes disproportionate burdens on the Platform or its systems. You agree to use, retain, and process personal data obtained from the Platform in accordance with applicable laws, rules, and regulations, and only for the purpose of administering and participating in LessonBucket events. Without limitation, you agree to inform individuals whose personal data you wish to process to obtain the necessary consents and respond to their requests as required by law. You also agree to protect such data from unauthorized access or processing. You must delete personal data as soon as it is no longer strictly necessary for the administration of a LessonBucket event or promptly upon receiving a request from LessonBucket, and you will promptly certify the deletion thereof.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>4.6 Platform Modifications.</b> We strive to continually improve our Platform. This means we may modify or terminate parts or all of our Platform with or without notice, and without incurring liability to you or any third party.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>4.7 Third-Party Sites and Services.</b> The Platform contains links to third-party sites and is integrated with various third-party services, applications, and sites that may make their content and products available to you. We do not control these third parties and are not responsible for these sites or services, or their content or products. These third parties may have their own terms and policies, and your use of them will be governed by those terms and policies. You are not licensed to use third-party intellectual property simply by accessing our Platform.</p>
                        <h6 className="text-terms mx-5 mt-3 mb-3"><b>5. Rights you grant us.</b></h6>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>Summary:</b> You grant LessonBucket certain rights to use and share your Content on our Platform. You retain ownership of your Content.</p>
                        <h6 className="text-terms mx-5 mt-3 mb-3">10. General Conditions</h6>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>Summary:</b> This section contains conditions we have added for various purposes. Please read carefully.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>10.2 Notices.</b> Unless otherwise specified in this Agreement, or unless expressly required by local law, all notices to LessonBucket must be sent by certified mail to LessonBucket, Attn: Legal Department, Madrid, Spain, or by email to legal@LessonBucket.com. All notices directed to you will be sent to the most current email address on your account.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>10.3 Entire Agreement.</b> This Agreement, including the Usage and Content Policies, Event Policies, Organizer and Organizer Team Standards, Membership Restrictions, Intellectual Property Policies, and Trademark Use Guidelines, constitutes the entire agreement between you and LessonBucket, replacing any previous agreement you and LessonBucket may have entered into for the same purpose.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>10.4 Absence of Agency.</b> This Agreement is not intended to create, nor does it create, an agency, partnership, joint venture, employer-employee relationship, or franchise relationship between you and LessonBucket. A LessonBucket Platform member is not a representative or agent of LessonBucket and cannot enter into an agreement on behalf of LessonBucket.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>10.5 Applicable Law.</b> This Agreement and the relationship between you and LessonBucket will be governed by the laws of the European Union, regardless of conflict of law provisions, except as provided in section 8.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>10.6 Judicial Forum.</b> If it is determined that our arbitration agreement does not apply to you or your claim, or if you opt-out of arbitration pursuant to section 8.4, you and LessonBucket agree that any judicial proceeding (other than small claims actions) must be conducted exclusively in the federal or state courts located in Madrid, Spain, and you and LessonBucket consent to the jurisdiction and personal jurisdiction of those courts. Additionally, the European Commission offers an online dispute resolution platform for residents of the European Union.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>10.7 Time for Filing.</b> Any claim not subject to arbitration must be commenced within one year from the date the party bringing the claim first knows or reasonably should know of the act, omission, or breach giving rise to the claim, or the shortest period allowed by applicable law. This provision does not affect you if you reside in the EU.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>10.8 Assignment.</b> You may not assign, transfer, or sublicense this Agreement without the prior written consent of LessonBucket, but this Agreement may be assigned or transferred by us to any parent, subsidiary, or affiliate, or by reason of a merger, acquisition, corporate reorganization, sale of all or substantially all of LessonBucket's assets, or similar transaction.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>10.9 No Waivers.</b> If a party does not exercise or enforce any right or provision of this Agreement, that does not constitute a waiver of that right or provision, and it does not waive any right to act with respect to subsequent or similar breaches.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>10.10 Partial Invalidity.</b> If a competent court concludes that any provision of this Agreement is invalid, you and LessonBucket agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the remaining provisions of this Agreement will remain in full force and effect.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>10.11 Gratitude.</b> We sincerely thank you for reading our Terms of Use.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>10.12 Termination.</b> If we cancel your account or access to our Platform, this Agreement will terminate with respect to the member's account that has been canceled, provided that the provisions set forth in section 10.13 remain in effect after such termination.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>10.13 Preservation of Effectiveness.</b> Sections 3.2 (License granted by you over content), 3.3 (Privacy), 5 (Disclaimers), 6 (Indemnification), 7 (Warranties Disclaimer and Limitation of Liability), 8 (Dispute Resolution), and 10 (General Conditions) of this Agreement, and any other provisions necessary to give effect to these provisions, shall survive termination or expiration of this Agreement.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>10.14 Titles.</b> The section titles in this Agreement are for convenience only and have no legal or contractual effect. The information contained in the sections "Summary of Terms of Use," "Tips," and "Summary" also serves a practical purpose and has no legal or contractual effect.</p>
                        <p className="text-terms mx-5 mt-3 mb-3"><b>10.15 Violations.</b> Please inform us of any violations of this Agreement by a member or a third party by sending an email to LessonBucket@gmail.com.</p>

                    </div>
                </div>
            </div>

        </>
    );
};